platform :ios, '9.0'

#屏蔽三方框架警告
inhibit_all_warnings!

target 'SwiftTool' do

  use_frameworks!

	pod 'SnapKit'
    pod 'Alamofire'
    pod 'Cache'
    pod 'CocoaChainKit'
    pod 'Toast-Swift'
    pod 'WKWebViewJavascriptBridge'
    pod 'MJRefresh'
    pod 'Charts'
    
    pod 'CocoaDebug'

				    
end

