platform :ios, '9.0'

target 'SwiftTool' do

  use_frameworks!

	pod 'SnapKit'
	pod 'Alamofire'
	pod 'Cache'
	pod 'CocoaChainKit'
	pod 'Toast-Swift'
	pod 'WKWebViewJavascriptBridge'
    pod 'MJRefresh'
			    
	pod 'CocoaDebug'
				    
end

